version: '3'
services:
  app:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "13000:3000"
    command: bundle exec rails s -p 3000  -b '0.0.0.0'
  mysql:
    image: "mysql:5.6"
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: "redis"
    ports:
      - "6379:6379"
volumes:
  mysql_db:
    driver: local
  
    
