version: '3'
services:
  app: &base
    container_name: docker_app
    build: .
    volumes:
      - .:/myapp
      - ./tmp/cache:/myapp/tmp/cache
      - ./log:/myapp/log
      - bundle_install:/myapp/vendor/bundle
      - sync-volume:/myapp
    ports:
      - "3000:3000"
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOSTNAME: mysql
      CACHE_STORE_URI: redis://redis:6379/0/cache
      SESSION_STORE_URI: redis://redis:6379/0/session
#  postgres:
#    image: "postgres"
#    volumes:
#      - postgres_db:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
  spring:
    <<: *base
    container_name: docker_spring
    command: ["/root/docker-scripts/spring.sh"]
    ports: []
  mysql:
    container_name: docker_mysql
    image: "mysql:5.7"
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    container_name: docker_redis
    image: "redis"
    ports:
      - "6379:6379"
  localstack:
    container_name: docker_localstack
    image: localstack/localstack
    ports:
      - "4572:4572"
volumes:
  mysql_db:
    driver: local
#  postgres_db:
#    driver: local
  bundle_install:
    driver: local
  sync-volume:
    external: true
