version: '3'
services:
  mysql:
    image: "mysql:5.6"
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  bash:
    image: "ubuntu"
    command: bash
