version: '3'
services:
  app:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "13000:3000"
    command: bundle exec rails s -p 3000  -b '0.0.0.0'
    environment:
      MYSQL_HOSTNAME: mysql
      CACHE_STORE_URI: redis://redis:6379/0/cache
      SESSION_STORE_URI: redis://redis:6379/0/session
#  postgres:
#    image: "postgres"
#    volumes:
#      - postgres_db:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
  mysql:
    image: "mysql:5.6"
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: "redis"
    ports:
      - "6379:6379"
volumes:
  mysql_db:
    driver: local
#  postgres_db:
#    driver: local
    
